language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install nose
  - pip install -e .
script: nosetests -w tests
jobs:
  include:
    - stage: deploy
      python: 3.6
      install: pip install twine
      script:
        - python setup.py sdist bdist_wheel
        - twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
      if: tag IS present

